# Site settings
title: PIC16A
subtitle: Python with Applications
description: 
baseurl: "/PIC16A/" # the subpath of your site, e.g. /blog/
url: "http://philchodrow.github.io/PIC16A" # the base hostname & protocol for your site
syllabus: "http://philchodrow.github.io/PIC16A/syllabus/"
materials: "http://philchodrow.github.io/PIC16A/materials/"
resources: "http://philchodrow.github.io/PIC16A/resources/" 
schedule: "http://philchodrow.github.io/PIC16A/schedule/" 
project: "http://philchodrow.github.io/PIC16A/project/" 
githubdir: "philchodrow/PIC16A"

# Author/user information
email: phil@math.ucla.edu
twitter_username: philchodrow
github_username:  philchodrow
authorurl: "http://www.philchodrow.com"
address: |
    Department of Mathematics
    UCLA


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
